export const dummyUsers = [
  {
    id: '1',
    name: 'Kelvin Samson',
    email: 'kelvin@sample.com',
    photoUrl: 'https://media.giphy.com/media/10VjiVoa9rWC4M/giphy.gif',
    role: 'Member',
    info: 'Product Designer at Facebook',
    welcomeMessage: 'Hey there! Love to chat :-)',
  },
  {
    id: '2',
    name: 'Annabel Stone',
    email: 'annie@sample.com',
    photoUrl: 'https://media.giphy.com/media/iFW661Tf7Mp1e/giphy.gif',
    role: 'Member',
    info: 'Digital Marketer at Microsoft',
    welcomeMessage: 'Hey there! Love to chat :-)',
  },
  {
    id: '3',
    name: 'Grace Loveday',
    email: 'grace@sample.com',
    photoUrl: 'https://media.giphy.com/media/rQzk820Dmcc2Q/giphy.gif',
    role: 'Member',
    info: 'Product Designer at Google',
    welcomeMessage: 'Hey there! Love to chat :-)',
  },
  {
    id: '4',
    name: 'Angela Jobs',
    email: 'angela@sample.com',
    photoUrl: 'https://media.giphy.com/media/rTwxsNsR6iwfK/giphy.gif',
    role: 'Member',
    info: 'Software Engineer at TalkJS',
    welcomeMessage: 'Hey there! Love to chat :-)',
  },
];
